<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.fushuwei</groupId>
        <artifactId>sca-skeleton-backend</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>sca-skeleton-starters</artifactId>
    <packaging>pom</packaging>

    <name>SCA Skeleton Backend :: Starters</name>
    <description>Reusable backend starters</description>

    <modules>
        <module>sca-skeleton-starter-core</module>
        <module>sca-skeleton-starter-web</module>
        <module>sca-skeleton-starter-logging</module>
        <module>sca-skeleton-starter-captcha</module>
        <module>sca-skeleton-starter-redis</module>
        <module>sca-skeleton-starter-mybatis-plus</module>
        <module>sca-skeleton-starter-feign</module>
    </modules>
</project>
