server:
  port: 9999

spring:
  application:
    name: sca-skeleton-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9000
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: sca-auth-protocol
              uri: http://127.0.0.1:9000
              predicates:
                - Path=/oauth2/**,/.well-known/**,/userinfo,/login/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
