server:
  port: 9999

spring:
  application:
    name: sca-skeleton-gateway
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      discovery:
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_DISCOVERY_GROUP:DEFAULT_GROUP}
      config:
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_CONFIG_GROUP:DEFAULT_GROUP}
  config:
    import:
      - optional:classpath:${spring.application.name}-${spring.profiles.active}.yaml
      - optional:nacos:sca-skeleton-common.yaml
      - optional:nacos:${spring.application.name}.yaml
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
