<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.fushuwei</groupId>
        <artifactId>sca-skeleton-starters</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>sca-skeleton-starter-redis</artifactId>
    <packaging>jar</packaging>

    <name>SCA Skeleton Backend :: Starter :: Redis</name>
    <description>Redis reusable components</description>

    <dependencies>
        <!-- Starter Core -->
        <dependency>
            <groupId>io.github.fushuwei</groupId>
            <artifactId>sca-skeleton-starter-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <!-- Spring Data Redis -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>
    </dependencies>
</project>
