<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.fushuwei</groupId>
        <artifactId>sca-skeleton-starters</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>sca-skeleton-starter-doc</artifactId>
    <packaging>jar</packaging>

    <name>SCA Skeleton Backend :: Starter :: Doc</name>
    <description>SCA Skeleton Backend :: API 文档 Starter（SpringDoc OpenAPI 3 + Swagger UI）</description>

    <dependencies>
        <!-- 项目核心 Starter（自定义基础组件封装） -->
        <dependency>
            <groupId>io.github.fushuwei</groupId>
            <artifactId>sca-skeleton-starter-core</artifactId>
        </dependency>

        <!-- SpringDoc OpenAPI 文档（基于 WebMVC + Swagger UI） -->
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
        </dependency>

        <!-- 配置元数据处理器（为自定义配置类提供 IDE 自动补全与元数据生成功能） -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>
</project>
